### ISSUE TITLE
generator: Consider removing @BetaApi from client header customization surface

### ISSUE THREAD

**Issue by burkedavison** [googleapis/sdk-platform-java#2100]
1. Client stub settings
    * Example: https://github.com/googleapis/google-cloud-java/blob/main/java-iot/google-cloud-iot/src/main/java/com/google/cloud/iot/v1/stub/DeviceManagerStubSettings.java#L454-L471
    * Generation logic: https://github.com/googleapis/sdk-platform-java/blob/decd7f60017d45288e6c12493fa21e06f9c5f77c/gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/common/AbstractServiceStubSettingsClassComposer.java#L374

2. Client settings
    * Example: https://github.com/googleapis/google-cloud-java/blob/main/java-iot/google-cloud-iot/src/main/java/com/google/cloud/iot/v1/DeviceManagerSettings.java#L234-L237
    * Generation logic: https://github.com/googleapis/sdk-platform-java/blob/decd7f60017d45288e6c12493fa21e06f9c5f77c/gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/common/AbstractServiceSettingsClassComposer.java#L436

**Comment by diegomarquezp** [comment]
cc: @blakeli0 
Unless there are plans to change the header customization surface in the future, this surface is otherwise stable and we should remove the annotation

## Generator Classes
### `AbstractServiceSettings`
__How long has this API been around?__
[3 years](https://github.com/googleapis/sdk-platform-java/blame/decd7f60017d45288e6c12493fa21e06f9c5f77c/gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/common/AbstractServiceSettingsClassComposer.java#L427-L441)

__How much variation occured in the API over time?__
The method generation [code](https://github.com/googleapis/sdk-platform-java/blame/decd7f60017d45288e6c12493fa21e06f9c5f77c/gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/common/AbstractServiceSettingsClassComposer.java#L331-L344)'s last change was 3 years ago.



### `AbstractServiceStubSettings`
__How long has this API been around?__
[2+ years](https://github.com/googleapis/sdk-platform-java/blame/decd7f60017d45288e6c12493fa21e06f9c5f77c/gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/common/AbstractServiceStubSettingsClassComposer.java#L322-L387)

__How much variation occured in the API over time?__
The generator method has not changed since its first implementation

## Gax classes
### `ApiClientHeaderProvider`
__How long has this API been around?__
[6 years](https://github.com/googleapis/sdk-platform-java/blame/main/gax-java/gax/src/main/java/com/google/api/gax/rpc/ApiClientHeaderProvider.java#L41)

__How much variation occured in the API over time?__
[Last change](https://github.com/googleapis/sdk-platform-java/blame/main/gax-java/gax/src/main/java/com/google/api/gax/rpc/ApiClientHeaderProvider.java#L43) was ~4 years ago
