### ISSUE TITLE
Generator should skip generation for empty services

### ISSUE THREAD

**Issue by alicejli** [googleapis/sdk-platform-java#2750]
A scenario came up with https://github.com/googleapis/google-cloud-java/pull/10802 where https://github.com/googleapis/googleapis/blob/master/google/cloud/visionai/v1/prediction.proto contains an empty service (e.g. no RPCs). 

There tests fail when trying to compile the generated library containing this proto which means the generator is generating some classes for this empty service which are not compilable. The generator instead should skip generation for an empty service.

**Comment by blakeli0** [comment]
Similar issue https://github.com/googleapis/sdk-platform-java/issues/2050 where the gapic generator errors out if no service exists.

**Comment by zhumin8** [comment]
> Possible solutions:
> 
> 1. Skip generation clients if no RPCs found for a service.
> 2. Generate an empty client, no ideal but maybe there is a use case for empty clients.

Currently I am opting for option 1 in #3051, to skip generation altogether if no RPCs found in a service (filter in parsing services). However, I run into a conflict with [this test](https://github.com/vam-google/gapic-generator-java/blob/7ca4aaaf100a106b04bcc0018c347624e35248f3/src/test/java/com/google/api/generator/gapic/composer/grpcrest/ServiceClientClassComposerTest.java#L42-L52), and discovered this relative old [pr](https://github.com/googleapis/sdk-platform-java/pull/985) that put on a check for empty services for sample composers.

- The above pr only fixes for sample code composers, thus we are still observing this behavior as reported in this issue.
- The behavior in above pr still generates samples for empty services, while [discussion](https://github.com/googleapis/sdk-platform-java/pull/985#:~:text=On%20the%20other%20hand%2C%20this,the%20team%20on%20maintaining%20nulls.) on the pr seams to suggest it was a quick fix to not error out and author and reviewers seems to have consensus that services without RPCs should not be a thing.
- this was originally a fix to enable sqladmin API, but I don’t see sql admin generated in google-cloud-java. Any context?

I want to run this quickly by @blakeli0  to check if you think it's okay to **not** generate clients for empty services that do not have RPCs? Or otherwise, is empty services like [this one](https://github.com/googleapis/googleapis/blob/master/google/cloud/sql/v1/cloud_sql_instance_names.proto#L31) a legit use case?

**Comment by blakeli0** [comment]
Thanks for the investigation @zhumin8 ! I don't think this is a legit use case, the [PR](https://github.com/googleapis/sdk-platform-java/pull/985) was probably trying to resolve a presubmit check internally when this proto was introduced. 
Since the specific service never request generation for a Java library, means there would be no breaking change once this issue is fixed, I think we are safe to not generating clients for empty services.
